<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutputType>Exe</OutputType>
        <!--
        To enable the Microsoft Testing Platform 'dotnet test' experience, add property:
          <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

        To enable the Microsoft Testing Platform native command line experience, add property:
          <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>

        For more information on Microsoft Testing Platform support in xUnit.net, please visit:
          https://xunit.net/docs/getting-started/v3/microsoft-testing-platform
        -->
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="SimdLinq"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="BookTests\gm2600.bin"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="BookTests\gm2600.bin">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\perft\Rudzoft.Perft.Settings\Rudzoft.Perft.Settings.csproj"/>
        <ProjectReference Include="..\Rudzoft.ChessLib\Rudzoft.ChessLib.csproj"/>
    </ItemGroup>

</Project>
