<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Platforms>AnyCPU</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\chess-lib\Rudzoft.ChessLib\Rudzoft.ChessLib.csproj" />
        <ProjectReference Include="..\..\perft\Rudzoft.Perft\Rudzoft.Perft.csproj" />
    </ItemGroup>

</Project>
