<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Akka"/>
      <PackageReference Include="Akka.DependencyInjection"/>
      <PackageReference Include="Akka.Hosting" />
      <PackageReference Include="Serilog"/>
      <PackageReference Include="Serilog.Sinks.Console"/>
      <PackageReference Include="Serilog.Sinks.File"/>
      <PackageReference Include="Serilog.Settings.Configuration"/>
      <PackageReference Include="Serilog.Enrichers.Thread"/>
      <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\chess-lib\Rudzoft.ChessLib\Rudzoft.ChessLib.csproj" />
      <ProjectReference Include="..\Rudzoft.Perft.Settings\Rudzoft.Perft.Settings.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="appsettings.json"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageVersion Update="Akka.Persistence.PostgreSql.Hosting" Version="1.5.20" />
    </ItemGroup>

</Project>
